version = 0.1

[default.global.parameters]
stack_name = "wellmed-backend"

[default.build.parameters]
cached = true
parallel = true
use_container = false

[default.deploy.parameters]
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
fail_on_empty_changeset = false
parameter_overrides = "Stage=prod"
